AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Project Rakan - AWS Serverless IoT Automation System

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Runtime: python3.11

Resources:
  RakanDeviceStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: rakan-devicestate
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  RakanIngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rakan-ingest
      Handler: app.lambda_handler
      CodeUri: lambdas/ingestLambda/
      Environment:
        Variables:
          TABLE_NAME: rakan-devicestate
          IOT_ENDPOINT: '' # Set in deployment
          DECISION_FUNCTION_NAME: rakan-decision
      Policies:
        - DynamoDBCrudPolicy:
            TableName: rakan-devicestate
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !GetAtt RakanDecisionFunction.Arn
        - CloudWatchLogsPolicy: {}

  RakanDecisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rakan-decision
      Handler: app.lambda_handler
      CodeUri: lambdas/decisionLambda/
      Environment:
        Variables:
          TABLE_NAME: rakan-devicestate
          IOT_ENDPOINT: '' # Set in deployment
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: !GetAtt RakanDeviceStateTable.Arn
        - Statement:
            Effect: Allow
            Action:
              - iot:Publish
            Resource: arn:aws:iot:*:*:topic/devices/*/commands
        - CloudWatchLogsPolicy: {}

  RakanCommandFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rakan-command
      Handler: app.lambda_handler
      CodeUri: lambdas/commandLambda/
      Environment:
        Variables:
          TABLE_NAME: rakan-devicestate
          IOT_ENDPOINT: '' # Set in deployment
      Policies:
        - DynamoDBCrudPolicy:
            TableName: rakan-devicestate
        - Statement:
            Effect: Allow
            Action:
              - iot:Publish
            Resource: arn:aws:iot:*:*:topic/devices/*/commands
        - CloudWatchLogsPolicy: {}

Outputs:
  DeviceStateTableName:
    Description: DynamoDB table name
    Value: !Ref RakanDeviceStateTable
  RakanIngestFunctionArn:
    Description: ARN of ingest Lambda
    Value: !GetAtt RakanIngestFunction.Arn
  RakanDecisionFunctionArn:
    Description: ARN of decision Lambda
    Value: !GetAtt RakanDecisionFunction.Arn
  RakanCommandFunctionArn:
    Description: ARN of command Lambda
    Value: !GetAtt RakanCommandFunction.Arn

# --- IoT Rule Example (manual creation) ---
# AWS::IoT::TopicRule
# Properties:
#   RuleName: rakan-ingest-rule
#   TopicRulePayload:
#     Sql: "SELECT * FROM 'devices/+/telemetry'"
#     Actions:
#       - Lambda:
#           FunctionArn: <rakan-ingest ARN>
